version: "3"

services: 
    www:
        build: .
        restart: always
        ports:
            - '80:80'
        volumes: 
            - ./app:/var/www/html
        networks: 
            - default
    db:
        image: mysql:5.7
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
        restart: always
        ports: 
            - '3306:3306'
        environment:
            TZ: America/Sao_Paulo 
            MYSQL_DATABASE: projeto_webjump
            MYSQL_USER: webjump
            MYSQL_PASSWORD: 676247307f67b84210663f19ff9878cd
            MYSQL_ROOT_PASSWORD: 676247307f67b84210663f19ff9878cd
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - default

volumes:
    db_data: